### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by Smarthome-Creator** [Hofferic/HomeAssistantLongRunningShellCommand#1]
Hello,

can you show us a sample configuration to use your integration?

**Comment by Hofferic** [comment]
The configuration is identical to the built-in shell command: https://www.home-assistant.io/integrations/shell_command/
You just need to replace the shell_command key with long_shell_command to use this one instead :)

**Comment by Smarthome-Creator** [comment]
Ok, thanks I try it out and I understand how it works.

I think it needs to be made clear that a new long_shell_command.yaml needs to be created and inserted into configuration.yaml. A newbie won't figure this out by himself.

And one last question. How long is the time out range in your custom component?

I do a lot of remote server actions like updates and backups and they sometimes take longer than 1 hour.

EDIT:
Just found your comment “10 minutes timeout”.

**Comment by Hofferic** [comment]
You don't _need_ to put it in a separate file. It just uses the regular configuration conventions of home assistant. 

Regarding long backup jobs, those should probably not be run directly from a shell command but rather just triggered or configured as a cron job.
This is mostly intended for semi-quick scripts or curl fetches which would break with the default timeout :)

**Comment by J-o-h-n-M** [comment]
> The configuration is identical to the built-in shell command: https://www.home-assistant.io/integrations/shell_command/ You just need to replace the shell_command key with long_shell_command to use this one instead :)

This should really be part of the readme.md

**Comment by Hofferic** [comment]
This was mostly done for my own use, so the readme is correspondingly sparse. But that is a good point, so I updated it :)

**Comment by J-o-h-n-M** [comment]
> This was mostly done for my own use, so the readme is correspondingly sparse. But that is a good point, so I updated it :)

Thanks for providing this btw, really saved me. I am running a ffmpeg command to create a timelapse that takes 2-3 minutes, works like a charm with your module.
